// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $add from "./routes/add.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AddForm from "./islands/AddForm.tsx";
import * as $Card from "./islands/Card.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $Selector from "./islands/Selector.tsx";
import * as $Times from "./islands/Times.tsx";
import * as $TopPortal from "./islands/TopPortal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/add.tsx": $add,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AddForm.tsx": $AddForm,
    "./islands/Card.tsx": $Card,
    "./islands/Counter.tsx": $Counter,
    "./islands/Header.tsx": $Header,
    "./islands/Selector.tsx": $Selector,
    "./islands/Times.tsx": $Times,
    "./islands/TopPortal.tsx": $TopPortal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
